FROM python:3.11-slim

WORKDIR /app

# TODO: Move this to a requirements.txt if more dependencies are added
RUN pip install --no-cache-dir paho-mqtt==2.1.0

# Copy the `poc` package so imports like `poc.client_publisher` work
COPY poc /app/poc

# Ensure Python finds /app on import path so `import poc` works
ENV PYTHONPATH=/app

ENV PYTHONUNBUFFERED=1

# Default envs; can be overridden in Kubernetes manifest
ENV BROKER_HOST=mqtt-broker
ENV BROKER_PORT=1883
ENV CLIENT_ID=publisher1
ENV TOPIC=db/ingest/device/device-1
ENV USER=device-1
ENV PURPOSE=ingest
ENV INTERVAL=5

CMD ["sh", "-c", "python poc/loop_publisher.py"]
