---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        # point to the in-cluster prometheus service installed by kube-prometheus-stack
        url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        isDefault: false
        version: 1
        editable: false