apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 15s
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingress-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
      scheme: http
